GET http://localhost:3000/api/autores

###

GET http://localhost:3000/api/autores/getById/2

###

POST http://localhost:3000/api/autores
Content-Type: application/json

{
    "nombre":"Autor7",
    "email":"autor7@autor7.com",
    "imagen":"imagen7.jpeg"
}

###

PUT http://localhost:3000/api/autores/5
Content-Type: application/json

{
    "nombre":"Autor5_",
    "email":"autor5@autor5_.com",
    "imagen":"imagen5_.jpeg"
}

###

DELETE http://localhost:3000/api/autores/6