GET http://localhost:3000/api/autores

###

GET http://localhost:3000/api/autores/getById/2

###

POST http://localhost:3000/api/autores
Content-Type: application/json

{
    "nombre":"Autor8",
    "email":"autor7@autor8.com",
    "imagen":"imagen8.jpeg"
}

###

PUT http://localhost:3000/api/autores/9
Content-Type: application/json

{
    "nombre":"Autor9_2",
    "email":"autor5@autor9_2.com",
    "imagen":"imagen9_2.jpeg"
}

###

DELETE http://localhost:3000/api/autores/9